# Generated by Django 5.2.13 on 2026-04-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel', '0012_classschedule_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
