# Generated by Django 5.2.13 on 2026-04-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel', '0013_etudiant_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('ready', 'Pret'), ('rejected', 'Refuse')], default='pending', max_length=20),
        ),
    ]
