# Generated by Django 5.2.13 on 2026-04-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel', '0014_alter_documentrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
