# Generated by Django 5.2.13 on 2026-05-04 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel', '0015_alter_etudiant_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='numero_etudiant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='etudiant',
            constraint=models.UniqueConstraint(fields=('filiere', 'numero_etudiant'), name='unique_student_number_per_class'),
        ),
    ]
